### ISSUE TITLE
Github Action should build the release version

### ISSUE THREAD

**Issue by Importantus** [hoppjan/luebeck-mensa-widget#30]
At the moment, the action builds and publishes a debug apk. For [coinsaw](https://github.com/Importantus/coinsaw) I already created an [action](https://github.com/Importantus/coinsaw/blob/master/.github/workflows/build.yaml) that instead builds the release version, but @hoppjan needs to add a signing key to the repo secrets, before I can implement it here. 

For more info on what you need to add, look at the linked action or the [article](https://medium.com/@dcostalloyd90/automating-android-builds-with-github-actions-a-step-by-step-guide-2a02a54f59cd), I followed for creating it.

**Comment by hoppjan** [comment]
I will take a look at it :)
