### ISSUE TITLE
Fix mensaDay calculation

### ISSUE THREAD

**Issue by Importantus** [hoppjan/luebeck-mensa-widget#47]
Currently, the code for calculating the date for which the meals should be fetched looks like this:
```kotlin
val LocalDateTime.mensaDay: LocalDate
    get() = when {
        date.dayOfWeek == SATURDAY -> date + 2.days
        date.dayOfWeek == SUNDAY || isAfterMensaHours -> date + 1.days
        else -> date
    }
```
The problem is that ` isAfterMensaHours -> date + 1.days` sets the date on friday to saturday, not the next monday.

**Comment by hoppjan** [comment]
This should definitely go into v0.0.6

Waiting on the review for #
