### ISSUE TITLE
Widget date

### ISSUE THREAD

**Issue by hoppjan** [hoppjan/luebeck-mensa-widget#48]
I think the date is a bit big and doesn't really fit with the rest of the layout. But this could maybe be a new issue.

_Originally posted by @Importantus in https://github.com/hoppjan/luebeck-mensa-widget/pull/39#discussion_r1759091522_

**Comment by hoppjan** [comment]
Maybe the year should get removed as well?

**Comment by Importantus** [comment]
Yes! I still quite like the mockup I made in #21

**Comment by hoppjan** [comment]
Left placement of date (day of week & short date) and the refresh button on the right side?

Maybe limit the date info to one line as well, so that it does not take up too much space.

What about scrolling behavior?; Should it be scrollabe or stay in place?

**Comment by hoppjan** [comment]
![image](https://github.com/user-attachments/assets/680bd3a2-8aef-4a79-b3f4-4e0f5e780e2d)

Maybe like this? @Importantus

**Comment by Importantus** [comment]
You could also shorten the day to two or three letters (Do.) for small layouts

**Comment by hoppjan** [comment]
I will either shorten them for all layouts or not at all. It makes it a lot more complex.

Would that be worth it?

**Comment by hoppjan** [comment]
This is the #21 mockup:
![#21 mockup](https://private-user-images.githubusercontent.com/48018197/280091737-859567f3-af54-413d-a66a-abbc99f80dea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNTkwNzQsIm5iZiI6MTcyNzM1ODc3NCwicGF0aCI6Ii80ODAxODE5Ny8yODAwOTE3MzctODU5NTY3ZjMtYWY1NC00MTNkLWE2NmEtYWJiYzk5ZjgwZGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDEzNTI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMGYyNGQzZGE3OGU5MDg5MzA0ZDQ1MjZkMzJlYWI3ZmY1ZDc2ZmIwZDg4YzFiMmI1NjVlZTFkYmQ3M2I2ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TsTmXJxZDCHq4JasmwyBiPBHN2mpZH-PIrt53S6Wjn8)
