### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by Importantus** [hoppjan/luebeck-mensa-widget#8]
As a user I want to be able to refresh the data displayed in the widget manually, without opening another app. In https://github.com/hoppjan/luebeck-mensa-widget/issues/21 I made a quick mockup how this could look.

**Comment by Draculente** [comment]
The API now supports to use the `/refresh` route to refresh its caches. As the expected behavior when refreshing the widget is to load the newest data available, it may be a good idea to first refresh the API cache before loading the new data.
